#!/usr/bin/tclsh
# Конвертация обычной даты в юлианский день
# Используется swetest и tcl
puts "Конвертация всемирного времени и обычной даты в юлианский день"
puts "Введите всемирное время в формате ЧЧ:ММ:СС "
set a [gets stdin]
puts "Введите обычную дату в формате ДД.ММ.ГГГГ "
set b [gets stdin]
set c [exec swetest -b$b -ut$a | grep ET: | cut -c 5-23]
puts "$a UTC $b = $c JD"
