#!/usr/bin/tclsh
# Конвертация юлианского дня в обычную дату и всемирное время
# Используется swetest и tcl
puts "Конвертация юлианского дня во всемирное время и обычную дату"
puts "Введите юлианский день формате 0000000.0000000"
set a [gets stdin]
set b [exec swetest -j$a | grep date | cut -c 12-36]
puts "$a JD = $b UTC"
